"""
Pydantic schemas for TwinSec Model V1.
These schemas validate the structure of models generated by LLMs.
"""
from typing import Optional, List, Dict, Any, Literal
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
import re


class SolverConfig(BaseModel):
    """Solver configuration for simulation."""
    method: Literal["euler", "rk4", "odeint"] = Field(default="euler", description="Numerical integration method")
    dt: float = Field(default=0.1, ge=0.001, le=10.0, description="Time step in seconds")
    max_duration: float = Field(default=300, ge=1, le=3600, description="Maximum simulation duration")


class Component(BaseModel):
    """A system component (tank, valve, sensor, etc.)."""
    id: str = Field(..., pattern=r"^[A-Za-z0-9_]+$", description="Unique component identifier")
    kind: str = Field(..., description="Type of component (plugin-specific)")
    params: Dict[str, Any] = Field(default_factory=dict, description="Component-specific parameters")
    initial_state: Optional[Dict[str, float]] = Field(default=None, description="Initial state variables")

    @field_validator('id')
    @classmethod
    def validate_id(cls, v: str) -> str:
        if not re.match(r"^[A-Za-z0-9_]+$", v):
            raise ValueError("Component ID must contain only alphanumeric characters and underscores")
        return v


class Connection(BaseModel):
    """Signal connection between components."""
    from_signal: str = Field(..., alias="from", pattern=r"^[A-Za-z0-9_]+\.[A-Za-z0-9_]+$")
    to_signal: str = Field(..., alias="to", pattern=r"^[A-Za-z0-9_]+\.[A-Za-z0-9_]+$")
    gain: float = Field(default=1.0, description="Signal gain/scaling factor")

    class Config:
        populate_by_name = True


class Signals(BaseModel):
    """Signal definitions for monitoring and control."""
    inputs: List[str] = Field(default_factory=list, description="External input signals")
    outputs: List[str] = Field(default_factory=list, description="Signals to monitor/export")


class HMIWidget(BaseModel):
    """HMI widget configuration."""
    kind: Literal["plot", "gauge", "slider", "switch", "tank_view", "valve_view"]
    bind: str = Field(..., description="Signal to bind (component_id.signal_name)")
    label: Optional[str] = None
    unit: Optional[str] = None
    min: Optional[float] = None
    max: Optional[float] = None


class Alarm(BaseModel):
    """Alarm/threshold configuration."""
    signal: str
    condition: Literal["gt", "lt", "eq", "ge", "le"]
    threshold: float
    severity: Literal["info", "warning", "critical"] = "warning"
    message: Optional[str] = None


class HMIConfig(BaseModel):
    """HMI configuration."""
    widgets: List[HMIWidget] = Field(default_factory=list)
    alarms: List[Alarm] = Field(default_factory=list)


class FDIAttack(BaseModel):
    """False Data Injection attack configuration."""
    target: str
    mode: Literal["constant", "bias", "replay", "random"]
    value: Optional[float] = None


class DoSAttack(BaseModel):
    """Denial of Service attack configuration."""
    target: str
    drop_rate: float = Field(ge=0.0, le=1.0)


class AttacksConfig(BaseModel):
    """Attack configurations."""
    fdi: List[FDIAttack] = Field(default_factory=list)
    dos: List[DoSAttack] = Field(default_factory=list)


class ModelMetadata(BaseModel):
    """Model metadata."""
    author: Optional[str] = None
    created_at: Optional[datetime] = None
    llm_provider: Optional[str] = None
    prompt_hash: Optional[str] = None


class TwinSecModelV1(BaseModel):
    """
    Complete TwinSec Model V1 schema.
    This is the core data structure for all simulation models.
    """
    name: str = Field(..., pattern=r"^[a-z0-9_]+$", min_length=3, max_length=50)
    type: Literal["tank", "microgrid_dc", "drone", "hvac", "custom"]
    version: Literal["1.0"] = "1.0"
    description: Optional[str] = Field(default=None, max_length=500)
    solver: SolverConfig
    components: List[Component] = Field(..., min_length=1)
    connections: List[Connection]
    signals: Optional[Signals] = None
    hmi: Optional[HMIConfig] = None
    attacks: Optional[AttacksConfig] = None
    metadata: Optional[ModelMetadata] = None

    @field_validator('name')
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not re.match(r"^[a-z0-9_]+$", v):
            raise ValueError("Model name must be lowercase alphanumeric with underscores")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "name": "tank_2v_demo",
                "type": "tank",
                "version": "1.0",
                "description": "A simple tank with 2 valves",
                "solver": {
                    "method": "euler",
                    "dt": 0.1,
                    "max_duration": 300
                },
                "components": [
                    {
                        "id": "T1",
                        "kind": "tank",
                        "params": {"area": 1.2, "h0": 0.3, "hmax": 2.0}
                    },
                    {
                        "id": "V_in",
                        "kind": "valve",
                        "params": {"Kv": 1.1}
                    },
                    {
                        "id": "V_out",
                        "kind": "valve",
                        "params": {"Kv": 0.9}
                    }
                ],
                "connections": [
                    {"from": "V_in.q", "to": "T1.q_in"},
                    {"from": "T1.h", "to": "V_out.h_up"}
                ],
                "signals": {
                    "outputs": ["T1.h", "V_in.q", "V_out.q"]
                }
            }
        }
